apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "gitops-operator.labels" . | indent 4 }}
  name: gitops-operator-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
{{ include "gitops-operator.labels" . | indent 6 }}
  sessionAffinity: None
  type: ClusterIP
